SRCS 		= ft_display_file.c

NAME		= ft_display_file
CC		= gcc
CFLAGS		= -Wall -Werror -Wextra

.PHONY:		all clean fclean

all:
		${CC} ${CFLAGS} ${SRCS} -o ${NAME}

clean:
		rm -f srcs/*.o *.o

fclean:
		rm -f ${NAME}
